development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mydatabase_dev
  pool: 5
  username: root
  password: password
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mydatabase_prod
  pool: 5
  username: root
  password: password
  host: localhost
