development:
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: false
  database: mydatabase_dev
  pool: 5
  username: root
  password: password
  host: localhost

production:
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: false
  database: mydatabase_prod
  pool: 5
  username: root
  password: password
  host: localhost
