development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mydb_dev
  pool: 5
  username: root
  password: password
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mydb_prod
  pool: 5
  username: root
  password: password
  host: localhost
