#secret.yml
hash_key:
  development: gargbababaenb9i5tgm
  production: argau83b98ungbkbae@
session_key:
  development: argau83bagrka01wbsbagjaoa
  production: argau83bagrka01wbsbagjaoa
basic_auth_realm:
  development: realm
  production: realm
basic_auth_name:
  development: admin
  production: 8ungbsfb8h
basic_auth_pass:
  development: password
  production: k9byhn7znb
