session_key:
  development: argau83bagrka01wbsbagjaoa
  production: argau83bagrka01wbsbagjaoa
fb_app_id:
  development: facebook_app_id
  production: facebook_app_id
fb_app_secret:
  development: facebook_app_secret
  production: facebook_app_secret
