source "https://supermarket.getchef.com"

cookbook 'git', '= 4.0.2'
cookbook 'iptables', path: './site-cookbooks/iptables'
cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-rbenv.git', :branch => 'v0.7.2'
cookbook 'nginx', '= 2.7.4'
cookbook 'yum-mysql-community', '~> 0.1.10'
cookbook 'mysql-community-server', path: './site-cookbooks/mysql-community-server'
cookbook 'imagemagick', '~> 0.2.3'
